import type { Metadata } from 'next'
// import { Inter } from 'next/font/google'
import { Fira_Code } from 'next/font/google'
import './globals.css'
import React from "react";
import Header from "@/components/header";
import Footer from "@/components/footer";

// const inter = Inter({ subsets: ['latin'] })

const firaCode = Fira_Code({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${firaCode.className} bg-gray-950 text-white`}>
      <Header />
      {children}
      <Footer />
      </body>
    </html>
  )
}
